
# This workflow will build the docker image and push to Azure Container Registry
# This workflow will do a clean install of python dependencies, run tests, build the docker images and deploy to Azure Container Instances

name: build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          registry: siscdatacr.azurecr.io
          name: siscdatacr.azurecr.io/sisc-decision-support-tool2
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
